name: Meu primeiro pipeline

on:
  push:
    branches:
      - main

jobs:
  teste01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listando var de ambiente
        run: |
          env

